version: '3.8'

services:
  api:
    build:
      context: src/
      dockerfile: Dockerfile
    container_name: api
    restart: on-failure
    command: sh -c "alembic upgrade head && python main.py"
    ports:
      - "8000:8000"
    env_file:
      - ${ENV_FILE:-.env}
    depends_on:
      - db

  db:
    image: postgres:15.0-alpine
    container_name: db
    restart: on-failure
    ports:
      - "5432:5432"
    env_file:
      - ${ENV_FILE:-.db.env}